### PR TITLE
Update de_de.json

### PR DESCRIPTION
**Pull request by Michiocre**

### CODE REVIEW

**Comment by chylex** [comment]
Thanks a lot! Is there any translation for `Tap` and `Hold`, or do they just stay like that?

**Comment by Michiocre** [comment]
I overlooked those, they are now changed, but the words are pretty long so.
Im also not sure if its the correct translation but it should fit.

**Comment by chylex** [comment]
Missed `Tap` and `Hold` in `bs.sprint.hold.info`, idk if you can just use the same word or if it needs different inflection there.

**Comment by Michiocre** [comment]
Sry for making you look over it 3 times xD but it should all be fixed now.
I even found some more mistakes.

**Comment by chylex** [comment]
Yea the words are pretty long lol. If there aren't any shorter words then I guess it'll be fine, I noticed even in vanilla some languages don't fit on buttons properly...

Where can I cut `Halte die Sprint-Taste gedrückt um im Kreativ- und Zuschauermodus schneller zu fliegen.` into two lines?

**Comment by Michiocre** [comment]
You can cut pretty much everywhere between the words doesnt really matter. Best would be after kreativ- but if it doesnt fit its fine.

I used shorter words but the translation is kinda wierd now but i think almost everyone will get it. And theres always the info.

**Comment by chylex** [comment]
Looks good, thanks!

**Pull request merged**
