### PR TITLE
Serbian translation

### PR DESCRIPTION
**Pull request by MCEventHorizon**
Hopefully I did this right.

### CODE REVIEW

**Comment by chylex** [comment]
The PR deletes the original english file. To fix that, please go to [your patch repository](https://github.com/MCEventHorizon/Better-Sprinting/tree/patch-1/src/main/resources/assets/bettersprinting/lang), click **Create new file**, call it **en_US.lang** and copy the contents from [the original file](https://raw.githubusercontent.com/chylex/Better-Sprinting/master/src/main/resources/assets/bettersprinting/lang/en_US.lang). That should restore the file and edit the PR.

**Comment by chylex** [comment]
en_US.lang is supposed to stay english, just copy the contents without changing anything. sr_SP.lang is correct.

**Comment by MCEventHorizon** [comment]
Says file with that name already exists.

**Comment by chylex** [comment]
You can edit it, click the pencil icon.

**Comment by chylex** [comment]
Looks good, thanks!

**Comment by MCEventHorizon** [comment]
Finally :D

**Comment by MCEventHorizon** [comment]
But now it says Serbian translation on en_US

**Comment by chylex** [comment]
It's fine, it only removed a line at the end of the file.

**Pull request merged**
