### PR TITLE
Create de_DE.lang

### PR DESCRIPTION
**Pull request by Vexatos**
something something you told me to something something.

Didn't translate the config because it makes no sense.

### CODE REVIEW

**Comment by chylex** [comment]
This means I can say the mod is officially endorsed by germans? :P

Thanks :3

**Comment by labpaw** [comment]
We also can try to ping @3TUSK and @Mazdallier for more localization

**Comment by Mazdallier** [comment]
Yep ! what's up ?

**Comment by labpaw** [comment]
Can you provide French localization for this mod?

**Comment by Mazdallier** [comment]
No problem, consider this is done...

**Comment by 3TUSK** [comment]
I will do it after school...

**Comment by Vexatos** [comment]
@Adaptivity Such a pity I don't have much time anymore... Glad you're still on it!

**Comment by labpaw** [comment]
I'm retired mostly. Doing some stuff very rare...

**Comment by 3TUSK** [comment]
@Adaptivity @Vexatos So do @crafteverywhere and @Mrkwtkr... I hope I can stay here...

**Comment by Mazdallier** [comment]
it's done. @3TUSK

**Pull request merged**
